### PR TITLE
PHP 8.0 support

### PR DESCRIPTION
**Pull request by GrahamCampbell**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| License         | MIT

I have:

- [x] Migrated the CI to GitHub Actions. **Actions runs will only show up after PR merge.**
- [x] Added PHP 8 to the CI and made any other needed changes.

#### EDIT: Actions run passes: https://github.com/GrahamCampbell/cache-plugin-1/actions/runs/167099786.

### CODE REVIEW

**Review by dbu — APPROVED** [review]

**Comment by GrahamCampbell** [comment]
phpspec is not ready yet: https://github.com/GrahamCampbell/client-common/runs/845397529?check_suite_focus=true

**Comment by GrahamCampbell** [comment]
Waiting on https://github.com/phpspec/phpspec/pull/1313 to be merged and tagged (with my fixes added to it too).

**Comment by dbu** [comment]
looks sane to me :+1: 

you tell me when it builds in your fork? then i can merge...

**Comment by GrahamCampbell** [comment]
@dbu Ready. :)

**Comment by GrahamCampbell** [comment]
@dbu This is ready now. :)

**Pull request merged**
